# https://github.com/Kareadita/Kavita

services:
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
        container_name: kavita
        volumes:
            - /mnt/drive/books:/books
            - /mnt/drive/.kavita/config:/kavita/config     # /kavita/config must not be changed
        environment:
            - TZ=Your/Timezone
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        ports:
            - "6000:5000"
        restart: unless-stopped
